# Generated by Django 4.2.26 on 2026-07-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_task_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="is_active",
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("in_review", "In Review"),
                    ("draft", "Draft"),
                    ("archived", "Archived"),
                    ("completed", "Completed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
