# Generated by Django 4.2.26 on 2026-08-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_remove_project_is_active_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("project_admin", "Project Admin"),
                    ("project_manager", "Project Manager"),
                    ("project_member", "Project Member"),
                    ("project_viewer", "Project Viewer"),
                ],
                default="project_viewer",
                max_length=20,
            ),
        ),
    ]
