# Generated by Django 4.2.26 on 2026-01-16 08:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APICollection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the collection",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the API collection", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of the collection's purpose",
                    ),
                ),
                (
                    "project_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Optional reference to a project (UUID for decoupling)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the collection is active",
                    ),
                ),
                (
                    "execution_order",
                    models.CharField(
                        choices=[
                            ("sequential", "Sequential (One after another)"),
                            ("parallel", "Parallel (Concurrent execution)"),
                        ],
                        default="sequential",
                        help_text="Default execution order for batch runs",
                        max_length=20,
                    ),
                ),
                (
                    "environment_variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Collection-level environment variables (key-value pairs)",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for categorization and filtering",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Collection",
                "verbose_name_plural": "API Collections",
                "db_table": "api_testing_collections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIEndpoint",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the API endpoint", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of what this API does",
                    ),
                ),
                (
                    "http_method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                            ("HEAD", "HEAD"),
                            ("OPTIONS", "OPTIONS"),
                        ],
                        default="GET",
                        help_text="HTTP method for the request",
                        max_length=10,
                    ),
                ),
                (
                    "url",
                    models.TextField(
                        help_text="API URL (supports {{variable}} placeholders)"
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Request headers as JSON object",
                    ),
                ),
                (
                    "query_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Query parameters as JSON object",
                    ),
                ),
                (
                    "request_body",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Request body/payload as JSON",
                    ),
                ),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("form-data", "Form Data"),
                            ("x-www-form-urlencoded", "URL Encoded"),
                            ("raw", "Raw Text"),
                            ("none", "No Body"),
                        ],
                        default="json",
                        help_text="Type of request body",
                        max_length=50,
                    ),
                ),
                (
                    "expected_status_code",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Expected HTTP status code (e.g., 200, 201)",
                        null=True,
                    ),
                ),
                (
                    "expected_response_contains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of keys/values expected in response",
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Request timeout in seconds",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Execution order within collection (lower = first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this endpoint is active",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of retry attempts on failure (0 = no retry)",
                    ),
                ),
                (
                    "retry_delay_seconds",
                    models.PositiveIntegerField(
                        default=1, help_text="Delay between retries in seconds"
                    ),
                ),
                (
                    "pre_request_script",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Python code to run before request (advanced)",
                    ),
                ),
                (
                    "post_response_script",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Python code to run after response (advanced)",
                    ),
                ),
                (
                    "extract_variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Variables to extract from response (key: json_path)",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Endpoint",
                "verbose_name_plural": "API Endpoints",
                "db_table": "api_testing_endpoints",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuthCredential",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this credential set", max_length=255
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("bearer", "Bearer Token"),
                            ("basic", "Basic Auth (Username/Password)"),
                            ("api_key", "API Key"),
                            ("api_key_header", "API Key (Header)"),
                            ("api_key_query", "API Key (Query Param)"),
                            ("oauth2", "OAuth 2.0"),
                            ("custom", "Custom Header"),
                            ("none", "No Authentication"),
                        ],
                        default="bearer",
                        help_text="Type of authentication",
                        max_length=20,
                    ),
                ),
                (
                    "encrypted_credentials",
                    models.BinaryField(
                        help_text="Encrypted credentials (never logged or exposed)"
                    ),
                ),
                (
                    "header_name",
                    models.CharField(
                        default="Authorization",
                        help_text="Header name for the auth token",
                        max_length=100,
                    ),
                ),
                (
                    "header_prefix",
                    models.CharField(
                        blank=True,
                        default="Bearer",
                        help_text="Prefix before token (e.g., 'Bearer', 'Token')",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When the credential expires", null=True
                    ),
                ),
                (
                    "auto_refresh",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically refresh token before expiration",
                    ),
                ),
                (
                    "refresh_url",
                    models.URLField(
                        blank=True, default="", help_text="URL for token refresh"
                    ),
                ),
                (
                    "refresh_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Payload for refresh request",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this credential was used",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auth Credential",
                "verbose_name_plural": "Auth Credentials",
                "db_table": "api_testing_auth_credentials",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionResult",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "endpoint_name",
                    models.CharField(
                        default="",
                        help_text="Snapshot of endpoint name (in case endpoint is deleted)",
                        max_length=255,
                    ),
                ),
                (
                    "endpoint_method",
                    models.CharField(
                        default="", help_text="Snapshot of HTTP method", max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="success",
                        max_length=20,
                    ),
                ),
                (
                    "request_url",
                    models.TextField(
                        help_text="Actual URL called (variables resolved)"
                    ),
                ),
                (
                    "request_headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Headers sent (sensitive values masked)",
                    ),
                ),
                (
                    "request_body",
                    models.JSONField(
                        blank=True, default=dict, help_text="Request body sent"
                    ),
                ),
                (
                    "response_status_code",
                    models.PositiveIntegerField(
                        blank=True, help_text="HTTP response status code", null=True
                    ),
                ),
                (
                    "response_headers",
                    models.JSONField(
                        blank=True, default=dict, help_text="Response headers received"
                    ),
                ),
                (
                    "response_body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Response body (truncated if large)",
                    ),
                ),
                (
                    "response_size_bytes",
                    models.PositiveIntegerField(
                        default=0, help_text="Original response size in bytes"
                    ),
                ),
                (
                    "execution_time_ms",
                    models.PositiveIntegerField(
                        default=0, help_text="Request execution time in milliseconds"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error details if request failed",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Type of error (e.g., ConnectionError, Timeout)",
                        max_length=100,
                    ),
                ),
                (
                    "assertions_passed",
                    models.BooleanField(
                        default=True,
                        help_text="Whether all assertions/expectations passed",
                    ),
                ),
                (
                    "assertion_details",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Details of assertion results",
                    ),
                ),
                (
                    "extracted_variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Variables extracted from this response",
                    ),
                ),
                (
                    "retry_attempt",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Which retry attempt this is (0 = first try)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Execution Result",
                "verbose_name_plural": "Execution Results",
                "db_table": "api_testing_execution_results",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("partial_failure", "Partially Failed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_apis",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of APIs to execute"
                    ),
                ),
                ("successful_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Execution"),
                            ("scheduled", "Scheduled Run"),
                            ("webhook", "Webhook Trigger"),
                            ("ci_cd", "CI/CD Pipeline"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "environment",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Environment variables used for this run",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional notes about this run",
                    ),
                ),
            ],
            options={
                "verbose_name": "Execution Run",
                "verbose_name_plural": "Execution Runs",
                "db_table": "api_testing_execution_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this schedule", max_length=255
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        help_text="Cron expression (e.g., '0 */6 * * *' for every 6 hours)",
                        max_length=100,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Timezone for the schedule",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                (
                    "next_run",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "notify_on_failure",
                    models.BooleanField(
                        default=True, help_text="Send notification when execution fails"
                    ),
                ),
                (
                    "notify_on_success",
                    models.BooleanField(
                        default=False,
                        help_text="Send notification on successful execution",
                    ),
                ),
                (
                    "notification_emails",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Email addresses for notifications",
                    ),
                ),
                (
                    "environment_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Environment variables to override for scheduled runs",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_runs",
                        to="api_testing.apicollection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Run",
                "verbose_name_plural": "Scheduled Runs",
                "db_table": "api_testing_scheduled_runs",
                "ordering": ["next_run"],
            },
        ),
    ]
