# Generated by Django 4.2.26 on 2026-01-16 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_testing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledrun",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="executionrun",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                help_text="Collection being executed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="execution_runs",
                to="api_testing.apicollection",
            ),
        ),
        migrations.AddField(
            model_name="executionrun",
            name="executed_by",
            field=models.ForeignKey(
                help_text="User who triggered the execution",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_execution_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="executionresult",
            name="api_endpoint",
            field=models.ForeignKey(
                help_text="API endpoint that was executed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="execution_results",
                to="api_testing.apiendpoint",
            ),
        ),
        migrations.AddField(
            model_name="executionresult",
            name="execution_run",
            field=models.ForeignKey(
                help_text="Parent execution run",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="api_testing.executionrun",
            ),
        ),
        migrations.AddField(
            model_name="authcredential",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                help_text="Collection this credential belongs to (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_credentials",
                to="api_testing.apicollection",
            ),
        ),
        migrations.AddField(
            model_name="authcredential",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_credentials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apiendpoint",
            name="collection",
            field=models.ForeignKey(
                help_text="Parent collection",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_endpoints",
                to="api_testing.apicollection",
            ),
        ),
        migrations.AddField(
            model_name="apiendpoint",
            name="depends_on",
            field=models.ForeignKey(
                blank=True,
                help_text="API that must run successfully before this one",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependents",
                to="api_testing.apiendpoint",
            ),
        ),
        migrations.AddField(
            model_name="apicollection",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this collection",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_collections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledrun",
            index=models.Index(
                fields=["is_active", "next_run"], name="api_testing_is_acti_edad42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledrun",
            index=models.Index(
                fields=["collection", "is_active"],
                name="api_testing_collect_640167_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="executionrun",
            index=models.Index(
                fields=["collection", "status", "-created_at"],
                name="api_testing_collect_04093b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="executionrun",
            index=models.Index(
                fields=["executed_by", "-created_at"],
                name="api_testing_execute_406aff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="executionrun",
            index=models.Index(
                fields=["status", "-started_at"], name="api_testing_status_26dc33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="executionresult",
            index=models.Index(
                fields=["execution_run", "status"],
                name="api_testing_executi_996659_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="executionresult",
            index=models.Index(
                fields=["api_endpoint", "-created_at"],
                name="api_testing_api_end_7a8ed4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="executionresult",
            index=models.Index(
                fields=["response_status_code"], name="api_testing_respons_90fe0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authcredential",
            index=models.Index(
                fields=["collection", "is_active"],
                name="api_testing_collect_72d68a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="authcredential",
            index=models.Index(
                fields=["auth_type", "is_active"], name="api_testing_auth_ty_4113df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiendpoint",
            index=models.Index(
                fields=["collection", "is_active", "sort_order"],
                name="api_testing_collect_4e03ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apiendpoint",
            index=models.Index(
                fields=["http_method", "is_active"],
                name="api_testing_http_me_4b06ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apicollection",
            index=models.Index(
                fields=["name", "is_active"], name="api_testing_name_7f912c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apicollection",
            index=models.Index(
                fields=["created_by", "is_active"],
                name="api_testing_created_233681_idx",
            ),
        ),
    ]
