# Generated by Django 4.2.26 on 2026-01-16 08:41

import apps.testing.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestResult",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("extracted_data", models.JSONField(default=dict)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("diff_data", models.JSONField(blank=True, default=dict)),
                ("debug_data", models.JSONField(blank=True, default=dict)),
                (
                    "debug_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.testing.models.debug_data_path,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "db_table": "test_results",
                "ordering": ["document__name"],
            },
        ),
        migrations.CreateModel(
            name="TestRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("api", "API"),
                            ("scheduled", "Scheduled"),
                            ("ci_cd", "CI/CD"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("summary_metrics", models.JSONField(blank=True, default=dict)),
                ("s3_output_path", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "db_table": "test_runs",
                "ordering": ["-created_at"],
            },
        ),
    ]
