# Generated by Django 4.2.26 on 2026-02-03 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "team_type",
                    models.CharField(
                        choices=[
                            ("development", "Development"),
                            ("qa", "QA"),
                            ("design", "Design"),
                            ("product", "Product"),
                            ("marketing", "Marketing"),
                            ("operations", "Operations"),
                            ("other", "Other"),
                        ],
                        default="development",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#1a1a2e", "Black"),
                            ("#3b82f6", "Blue"),
                            ("#8b5cf6", "Purple"),
                            ("#ec4899", "Pink"),
                            ("#ef4444", "Red"),
                            ("#22c55e", "Green"),
                            ("#f97316", "Orange"),
                            ("#14b8a6", "Teal"),
                        ],
                        default="#3b82f6",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "teams_team",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_members_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "teams_teammember",
                "ordering": ["-joined_at"],
                "indexes": [
                    models.Index(
                        fields=["team", "user"], name="teams_teamm_team_id_2f6292_idx"
                    ),
                    models.Index(fields=["role"], name="teams_teamm_role_bd3941_idx"),
                    models.Index(
                        fields=["deleted_at"], name="teams_teamm_deleted_6b5460_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="teammember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("team", "user"),
                name="unique_active_team_member",
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["name"], name="teams_team_name_43e047_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["team_type"], name="teams_team_team_ty_40b61e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["deleted_at"], name="teams_team_deleted_79b14a_idx"
            ),
        ),
    ]
