# Generated by Django 4.2.26 on 2026-06-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_contactmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("developer", "Developer"),
                    ("annotator", "Annotator"),
                    ("viewer", "Viewer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("developer", "Developer"),
                    ("annotator", "Annotator"),
                    ("viewer", "Viewer"),
                ],
                default="annotator",
                max_length=20,
            ),
        ),
    ]
