# Generated by Django 4.2.26 on 2026-06-04 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_alter_workspace_is_default"),
        ("users", "0005_alter_invitation_role_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, user is added to this workspace on acceptance. Otherwise added to default workspace.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitations",
                to="organizations.workspace",
            ),
        ),
    ]
