# Generated by Django 4.2.26 on 2026-06-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_invitation_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("local", "Local"),
                    ("google", "Google"),
                    ("microsoft", "Microsoft"),
                ],
                default="local",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="social_uid",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
