# Generated by Django 4.2.26 on 2026-07-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_auth_provider_user_social_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="source",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
