# Generated by Django 4.2.26 on 2026-08-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_contactmessage_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="central_user_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="User ID from Dyuksa Central backend. JWT user_id is resolved against this field — not the local id. Set when user is provisioned via Central webhook or migration.",
                null=True,
                unique=True,
            ),
        ),
    ]
