# Generated by Django 4.2.26 on 2026-01-16 08:41

import apps.groundtruth.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.groundtruth.models.document_upload_path,
                    ),
                ),
                ("source_file_url", models.URLField(blank=True, max_length=2000)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("image", "Image"),
                            ("json", "JSON"),
                            ("text", "Text"),
                            ("video", "Video"),
                            ("mp4", "MP4"),
                            ("other", "Other"),
                        ],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("field_reference", models.CharField(blank=True, max_length=255)),
                ("is_resolved", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "document_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="GTVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("gt_data", models.JSONField(default=dict)),
                ("change_summary", models.TextField(blank=True)),
                ("changes_from_previous", models.JSONField(blank=True, default=dict)),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("source_type", models.CharField(default="manual", max_length=50)),
                ("source_reference", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "gt_versions",
                "ordering": ["-version_number"],
            },
        ),
    ]
