# Generated by Django 4.2.26 on 2026-02-19 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("groundtruth", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentcomment",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="gtversion",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="organizations.organization",
            ),
        ),
    ]
