# Generated by Django 4.2.26 on 2026-02-20 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasksite", "0003_task_organization"),
        (
            "groundtruth",
            "0003_document_organization_documentcomment_organization_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="tasksite.task",
            ),
        ),
    ]
