# Generated by Django 4.2.26 on 2026-04-02 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_label_organization_project_organization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groundtruth", "0005_documentshare"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="documentshare",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="documentshare",
            name="shared_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_in_documents",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="documentshare",
            name="shared_with",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="documentshare",
            constraint=models.UniqueConstraint(
                fields=("document", "shared_with"), name="unique_document_user_share"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentshare",
            constraint=models.UniqueConstraint(
                fields=("document", "shared_project"),
                name="unique_document_project_share",
            ),
        ),
    ]
