# Generated by Django 4.2.26 on 2026-05-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groundtruth", "0006_alter_documentshare_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="preview_error",
            field=models.TextField(blank=True, help_text="Error if conversion failed"),
        ),
        migrations.AddField(
            model_name="document",
            name="preview_pdf",
            field=models.FileField(
                blank=True,
                help_text="Auto-generated PDF version for browser preview",
                null=True,
                upload_to="documents/previews/",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="preview_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                    ("not_needed", "Not Needed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
