# Generated by Django 4.2.26 on 2026-05-14 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groundtruth", "0008_folder_document_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentcomment",
            name="mentions",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentioned_in_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
