# Generated by Django 4.2.26 on 2026-05-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_label_organization_project_organization"),
        ("groundtruth", "0009_documentcomment_mentions"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="documents", to="projects.label"
            ),
        ),
    ]
