# Generated by Django 4.2.26 on 2026-01-16 08:41

import apps.issues.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("in_review", "In Review"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("wont_fix", "Won't Fix"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("bug", "Bug"),
                            ("task", "Task"),
                            ("improvement", "Improvement"),
                            ("gt_correction", "GT Correction"),
                            ("auto_generated", "Auto Generated"),
                        ],
                        default="bug",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("auto_generated", models.BooleanField(default=False)),
                ("error_category", models.CharField(blank=True, max_length=100)),
                ("error_pattern", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "issues",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IssueActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("status_changed", "Status Changed"),
                            ("priority_changed", "Priority Changed"),
                            ("assigned", "Assigned"),
                            ("unassigned", "Unassigned"),
                            ("label_added", "Label Added"),
                            ("label_removed", "Label Removed"),
                            ("comment_added", "Comment Added"),
                            ("attachment_added", "Attachment Added"),
                            ("link_added", "Link Added"),
                            ("resolved", "Resolved"),
                            ("reopened", "Reopened"),
                        ],
                        max_length=30,
                    ),
                ),
                ("old_value", models.CharField(blank=True, max_length=255)),
                ("new_value", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "issue_activities",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="IssueAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.issues.models.issue_attachment_path
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "issue_attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IssueComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "issue_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="IssueLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("gt_version", "GT Version"),
                            ("test_run", "Test Run"),
                            ("test_result", "Test Result"),
                            ("issue", "Related Issue"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "issue_links",
            },
        ),
    ]
