# Generated by Django 4.2.26 on 2026-03-24 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasksite", "0005_alter_task_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="pinned_by",
            field=models.ManyToManyField(
                blank=True, related_name="pinned_tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
