# Generated by Django 4.2.26 on 2026-07-03 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasksite", "0008_task_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="tasksite.task",
                verbose_name="Parent Task",
            ),
        ),
    ]
