# Generated by Django 4.2.26 on 2026-07-16 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=50)),
                ("display_name", models.CharField(max_length=150)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("pm", "Project Management"),
                            ("hrms", "HRMS"),
                            ("crm", "CRM"),
                            ("ims", "IMS / Finance"),
                            ("all", "All Platforms"),
                        ],
                        default="pm",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("data", "Data"),
                            ("administration", "Administration"),
                        ],
                        default="data",
                        max_length=20,
                    ),
                ),
                (
                    "field_scope",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "ordering": ["platform", "resource", "action"],
                "unique_together": {("resource", "action", "platform")},
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("pm", "Project Management"),
                            ("hrms", "HRMS"),
                            ("crm", "CRM"),
                            ("ims", "IMS / Finance"),
                            ("all", "All Platforms"),
                        ],
                        default="pm",
                        max_length=20,
                    ),
                ),
                (
                    "role_class",
                    models.CharField(
                        choices=[
                            ("platform", "Platform"),
                            ("functional", "Functional"),
                            ("custom", "Custom"),
                        ],
                        default="functional",
                        max_length=20,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=100)),
                ("display_name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default="")),
                ("is_system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_roles",
                        to="rbac.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["platform", "role_class", "code"],
                "unique_together": {("tenant_id", "code", "platform")},
            },
        ),
        migrations.CreateModel(
            name="ScopeNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("tenant", "Tenant"),
                            ("organization", "Organization"),
                            ("workspace", "Workspace"),
                            ("project", "Project"),
                            ("team", "Team"),
                            ("department", "Department"),
                            ("payroll_group", "Payroll Group"),
                            ("warehouse", "Warehouse"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scope_id", models.IntegerField()),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Scope Node",
                "verbose_name_plural": "Scope Nodes",
                "unique_together": {("scope_type", "scope_id")},
            },
        ),
        migrations.CreateModel(
            name="SodRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("is_mandatory", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("system", "System (Dyuksa)"),
                            ("admin", "Admin (Tenant)"),
                        ],
                        default="admin",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "permission_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sod_rules_as_a",
                        to="rbac.permission",
                    ),
                ),
                (
                    "permission_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sod_rules_as_b",
                        to="rbac.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "SoD Rule",
                "verbose_name_plural": "SoD Rules",
                "unique_together": {("tenant_id", "permission_a", "permission_b")},
            },
        ),
        migrations.CreateModel(
            name="ScopeClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depth", models.PositiveIntegerField(default=0)),
                (
                    "ancestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closure_as_ancestor",
                        to="rbac.scopenode",
                    ),
                ),
                (
                    "descendant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closure_as_descendant",
                        to="rbac.scopenode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scope Closure",
                "verbose_name_plural": "Scope Closures",
                "indexes": [
                    models.Index(fields=["ancestor"], name="rbac_closure_ancestor_idx"),
                    models.Index(
                        fields=["descendant"], name="rbac_closure_descendant_idx"
                    ),
                ],
                "unique_together": {("ancestor", "descendant")},
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_scope",
                    models.CharField(
                        choices=[
                            ("own", "Own records only"),
                            ("team", "Team records"),
                            ("department", "Department records"),
                            ("scope", "Scope records"),
                            ("all", "All records"),
                        ],
                        default="own",
                        max_length=20,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="rbac.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="rbac.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permission",
                "verbose_name_plural": "Role Permissions",
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("pm", "Project Management"),
                            ("hrms", "HRMS"),
                            ("crm", "CRM"),
                            ("ims", "IMS / Finance"),
                            ("all", "All Platforms"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("tenant", "Tenant"),
                            ("organization", "Organization"),
                            ("workspace", "Workspace"),
                            ("project", "Project"),
                            ("team", "Team"),
                            ("department", "Department"),
                            ("payroll_group", "Payroll Group"),
                            ("warehouse", "Warehouse"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scope_id", models.IntegerField()),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_assignments_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="rbac.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Assignment",
                "verbose_name_plural": "Role Assignments",
                "indexes": [
                    models.Index(
                        fields=["user", "platform", "valid_from", "valid_to"],
                        name="rbac_assign_user_platform_idx",
                    ),
                    models.Index(
                        fields=["scope_type", "scope_id"], name="rbac_assign_scope_idx"
                    ),
                ],
            },
        ),
    ]
