# Generated by Django 4.2.26 on 2026-01-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("task_created", "Task Created"),
                            ("task_assigned", "Task Assigned"),
                            ("task_status_updated", "Task Status Updated"),
                            ("task_completed", "Task Completed"),
                            ("task_comment", "Task Comment"),
                            ("project_created", "Project Created"),
                            ("project_assigned", "Project Assigned"),
                            ("project_member_added", "Project Member Added"),
                            ("project_updated", "Project Updated"),
                            ("mention", "Mention"),
                            ("reminder", "Reminder"),
                            ("system", "System Notification"),
                        ],
                        default="system",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("object_id", models.CharField(blank=True, max_length=255, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_notifications", models.BooleanField(default=True)),
                ("project_notifications", models.BooleanField(default=True)),
                ("mention_notifications", models.BooleanField(default=True)),
                ("system_notifications", models.BooleanField(default=True)),
                ("email_task_notifications", models.BooleanField(default=False)),
                ("email_project_notifications", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_preferences",
            },
        ),
    ]
