# Generated by Django 4.2.26 on 2026-03-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("task_created", "Task Created"),
                    ("task_assigned", "Task Assigned"),
                    ("task_status_updated", "Task Status Updated"),
                    ("task_completed", "Task Completed"),
                    ("task_comment", "Task Comment"),
                    ("project_created", "Project Created"),
                    ("project_assigned", "Project Assigned"),
                    ("project_member_added", "Project Member Added"),
                    ("project_updated", "Project Updated"),
                    ("document_shared", "Document Shared"),
                    ("mention", "Mention"),
                    ("reminder", "Reminder"),
                    ("system", "System Notification"),
                    ("new_message", "New Message"),
                ],
                default="system",
                max_length=50,
            ),
        ),
    ]
