# Generated by Django 4.2.26 on 2026-03-18 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quicknotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="quicknotes.folder",
            ),
        ),
    ]
