# Generated by Django 4.2.26 on 2026-04-06 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_label_organization_project_organization"),
        ("quicknotes", "0003_noteattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_notes",
                to="projects.project",
            ),
        ),
    ]
