# Generated by Django 4.2.26 on 2026-04-07 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quicknotes", "0004_note_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
