# Generated by Django 4.2.26 on 2026-05-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quicknotes", "0005_note_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="noteattachment",
            name="preview_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="noteattachment",
            name="preview_pdf",
            field=models.FileField(
                blank=True,
                help_text="Auto-generated PDF version for browser preview",
                null=True,
                upload_to="quicknotes/previews/%Y/%m/%d/",
            ),
        ),
        migrations.AddField(
            model_name="noteattachment",
            name="preview_status",
            field=models.CharField(
                default="pending",
                help_text="pending, processing, ready, failed, not_needed",
                max_length=20,
            ),
        ),
    ]
