export { Dashboard } from './Dashboard';
export { Login } from './Login';
export { Projects } from './Project/Projects';
export { ProjectCreate } from './Project/ProjectCreate';
export { DocumentCreate } from './Documents/DocumentCreate';
export { DocumentDetail } from './Documents/DocumentDetail';
export { MyTask } from './MyTask/MyTask';
export { CreateTask } from './MyTask/CreateTask'
export { CreateTeam } from './TeamManagement/CreateTeam';
export { UserManagement } from './TeamManagement/UserManagement'
export { TeamPerformance } from './TeamManagement/TeamPerformance';
export { TaskDetails } from './TaskType/TaskDetails'
export { ContentCreation } from './TaskType/ContentCreation';
export { Documents } from './Documents/Documents';
export { ProjectSettings } from './Project/ProjectSettings';
export { Sidebar } from '../components/layout/Sidebar';
export { Calendar } from './Calendar/Calendar';
export { NotificationsPage } from './NotificationsPage';
export { Profile } from  './Profile'
export { ResetPassword } from './ResetPassword'
export { TeamChatModern } from './TeamsChat/TeamChatModern'
