# Generated by Django 4.2.26 on 2026-01-28 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Room display name (auto-generated for private chats)",
                        max_length=255,
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("global", "Global Chat"),
                            ("project", "Project Chat"),
                            ("private", "Private Chat"),
                        ],
                        db_index=True,
                        default="private",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Unique identifier for WebSocket channel",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_chat_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_rooms",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatRoomMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_read_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "is_muted",
                    models.BooleanField(
                        default=False,
                        help_text="If true, user won't receive notifications",
                    ),
                ),
                (
                    "room_role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("moderator", "Moderator"),
                            ("admin", "Admin"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="chat.chatroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_room_memberships",
            },
        ),
        migrations.AddField(
            model_name="chatroom",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="chat_rooms",
                through="chat.ChatRoomMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated project for project-type rooms",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="projects.project",
            ),
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Message"),
                            ("image", "Image"),
                            ("file", "File Attachment"),
                            ("system", "System Message"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="Message text content"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="chat_attachments/%Y/%m/%d/"
                    ),
                ),
                (
                    "attachment_name",
                    models.CharField(
                        blank=True,
                        help_text="Original filename of attachment",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Message being replied to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="chat.chatmessage",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatroom",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageReadStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_statuses",
                        to="chat.chatmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_read_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_message_read_status",
                "indexes": [
                    models.Index(
                        fields=["message", "user"],
                        name="chat_messag_message_04cf6b_idx",
                    )
                ],
                "unique_together": {("message", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="chatroommembership",
            index=models.Index(
                fields=["user", "room"], name="chat_room_m_user_id_4d45e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroommembership",
            index=models.Index(
                fields=["last_read_at"], name="chat_room_m_last_re_95dcf8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatroommembership",
            unique_together={("user", "room")},
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["room_type", "is_active"], name="chat_rooms_room_ty_a475b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["project", "room_type"], name="chat_rooms_project_3e25af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["room", "created_at"], name="chat_messag_room_id_cc7f0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["sender", "created_at"], name="chat_messag_sender__7a605a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["room", "-created_at"], name="chat_messag_room_id_584819_idx"
            ),
        ),
    ]
