# Generated by Django 4.2.26 on 2026-02-05 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_team_favorited_by"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated team for team-type rooms",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("global", "Global Chat"),
                    ("project", "Project Chat"),
                    ("private", "Private Chat"),
                    ("team", "Team Chat"),
                ],
                db_index=True,
                default="private",
                max_length=20,
            ),
        ),
    ]
