# Generated by Django 4.2.26 on 2026-02-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatroom_team_alter_chatroom_room_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores link preview data or file metadata",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Message"),
                    ("image", "Image"),
                    ("file", "File Attachment"),
                    ("system", "System Message"),
                    ("link", "Link"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
