# Generated by Django 4.2.26 on 2026-02-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatmessage_metadata_alter_chatmessage_message_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroommembership",
            name="is_favourite",
            field=models.BooleanField(
                default=False,
                help_text="If true, this room is pinned or marked as favorite by the user",
            ),
        ),
    ]
