# Generated by Django 4.2.26 on 2026-02-23 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_chatmessage_organization_chatroom_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_ai_generated",
            field=models.BooleanField(
                default=False,
                help_text="True if this message was generated by the @zanflow AI",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                help_text="The original message this thread branched from",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_threads",
                to="chat.chatmessage",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("global", "Global Chat"),
                    ("project", "Project Chat"),
                    ("private", "Private Chat"),
                    ("team", "Team Chat"),
                    ("thread", "Thread Chat"),
                ],
                db_index=True,
                default="private",
                max_length=20,
            ),
        ),
    ]
