# Generated by Django 4.2.26 on 2026-03-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_chatmessage_is_ai_generated_chatroom_parent_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("global", "Global Chat"),
                    ("project", "Project Chat"),
                    ("private", "Private Chat"),
                    ("team", "Team Chat"),
                    ("thread", "Thread Chat"),
                    ("ai_bot", "AI Bot Chat"),
                ],
                db_index=True,
                default="private",
                max_length=20,
            ),
        ),
    ]
