# Generated by Django 4.2.26 on 2026-03-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_alter_chatroom_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="is_ai_generated",
            field=models.BooleanField(
                default=False,
                help_text="True if this message was generated by the @dyuksa AI",
            ),
        ),
    ]
