# Generated by Django 4.2.26 on 2026-05-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_alter_chatmessage_is_ai_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="preview_error",
            field=models.TextField(
                blank=True, help_text="Error if PDF conversion failed"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="preview_pdf",
            field=models.FileField(
                blank=True,
                help_text="Auto-generated PDF version of attachment for browser preview",
                null=True,
                upload_to="chat_attachments/previews/%Y/%m/%d/",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="preview_status",
            field=models.CharField(
                default="pending",
                help_text="pending, processing, ready, failed, not_needed",
                max_length=20,
            ),
        ),
    ]
