# Generated by Django 4.2.26 on 2026-05-20 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_workspace_workspacemembership"),
        ("chat", "0010_chatmessage_preview_error_chatmessage_preview_pdf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="organizations.workspace",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="organizations.workspace",
            ),
        ),
    ]
