# Generated by Django 4.2.26 on 2026-05-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organizationmember"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrganizationMember",
        ),
    ]
