# Generated by Django 4.2.30 on 2026-05-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_workspace_workspacemembership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
