# Generated by Django 4.2.26 on 2026-06-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_alter_workspace_is_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacemembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("developer", "Developer"),
                    ("annotator", "Annotator"),
                    ("viewer", "Viewer"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
