# Generated by Django 4.2.26 on 2026-07-08 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_alter_workspacemembership_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text='Short identifier used in JWT e.g. "pm", "hrms", "crm", "erp"',
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Human-readable name e.g. "Project Management"',
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional short description shown in the Admin Panel.",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Global switch — disable to hide this platform from all orgs.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform",
                "verbose_name_plural": "Platforms",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="PlatformAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Per-org switch — disable to revoke this org's access without deleting the row.",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_access",
                        to="organizations.organization",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_access",
                        to="organizations.platform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Access",
                "verbose_name_plural": "Platform Access",
                "ordering": ["organization", "platform__key"],
                "unique_together": {("organization", "platform")},
            },
        ),
    ]
