# Generated by Django 4.2.26 on 2026-04-09 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("daily_updates", "0002_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="parent_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="daily_updates.event",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="repeat_type",
            field=models.CharField(
                choices=[
                    ("none", "Does not repeat"),
                    ("daily", "Daily"),
                    ("workdays", "Every weekday (Mon-Fri)"),
                    ("weekly", "Weekly"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="repeat_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
