# Generated by Django 4.2.26 on 2026-04-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_updates", "0003_event_parent_event_event_repeat_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="repeat_until",
            new_name="recurrence_end_date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="parent_event",
        ),
        migrations.RemoveField(
            model_name="event",
            name="repeat_type",
        ),
        migrations.AddField(
            model_name="event",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="recurrence_group_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
