# Generated by Django 4.2.26 on 2026-04-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "daily_updates",
            "0004_rename_repeat_until_event_recurrence_end_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="recurrence",
        ),
        migrations.RemoveField(
            model_name="event",
            name="recurrence_end_date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="recurrence_group_id",
        ),
    ]
