# Generated by Django 4.2.26 on 2026-04-15 06:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("daily_updates", "0006_remove_event_attendees_eventinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                blank=True,
                related_name="attending_events",
                through="daily_updates.EventInvitation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
