# Generated by Django 4.2.26 on 2026-04-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_updates", "0007_event_attendees"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(default="Meeting", max_length=100),
        ),
    ]
